version: '3.8'

services:
  calculator:
    build:
      context: ./agent1_calculator
      dockerfile: Dockerfile
    container_name: calculator_agent
    ports:
      - "5001:5001"
    environment:
      - CALCULATOR_HOST=0.0.0.0
      - CALCULATOR_PORT=5001
      - UNIT_CONVERTER_HOST=unit_converter
      - UNIT_CONVERTER_PORT=5002
      - STATISTICS_HOST=statistics
      - STATISTICS_PORT=5003
    networks:
      - math_agents_network
    restart: unless-stopped

  unit_converter:
    build:
      context: ./agent2_unit_converter
      dockerfile: Dockerfile
    container_name: unit_converter_agent
    ports:
      - "5002:5002"
    environment:
      - UNIT_CONVERTER_HOST=0.0.0.0
      - UNIT_CONVERTER_PORT=5002
      - CALCULATOR_HOST=calculator
      - CALCULATOR_PORT=5001
      - STATISTICS_HOST=statistics
      - STATISTICS_PORT=5003
    networks:
      - math_agents_network
    restart: unless-stopped
    depends_on:
      - calculator

  statistics:
    build:
      context: ./agent3_statistics
      dockerfile: Dockerfile
    container_name: statistics_agent
    ports:
      - "5003:5003"
    environment:
      - STATISTICS_HOST=0.0.0.0
      - STATISTICS_PORT=5003
      - CALCULATOR_HOST=calculator
      - CALCULATOR_PORT=5001
      - UNIT_CONVERTER_HOST=unit_converter
      - UNIT_CONVERTER_PORT=5002
    networks:
      - math_agents_network
    restart: unless-stopped
    depends_on:
      - calculator

  # Test service to validate all agents
  agent_tester:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: agent_tester
    environment:
      - CALCULATOR_HOST=calculator
      - UNIT_CONVERTER_HOST=unit_converter
      - STATISTICS_HOST=statistics
    networks:
      - math_agents_network
    depends_on:
      - calculator
      - unit_converter
      - statistics
    profiles:
      - testing

networks:
  math_agents_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  agent_data:
